language: java
sudo: false
jdk:
- oraclejdk7
- oraclejdk8
- openjdk6
cache:
  directories:
  - $HOME/.m2/repository/
install: mvn --batch-mode dependency:go-offline
script: mvn --batch-mode install
after_success: ./etc/maybe-sonar.sh
deploy:
  skip_cleanup: true
  provider: script
  script: mvn --batch-mode --settings etc/ci-settings.xml deploy
  on:
    repo: grouplens/grapht
    branch: master
    jdk: oraclejdk7
branches:
  except:
  - stable
  - feature/sonar
env:
  global:
  # SONATYPE_USER
  - secure: "CZFHeyoLogfspHNAU2u2LskxKZnAup1znmOTptgMjSuMwVkZ+3czwZIirjv51cxwsYfQGUkA/FdyCCmpjBgDud5WJGteXIOphAj6A415hSZhKtvN10axw9ptx1oSEsvxgyCwa/V4U3vxvs0kgcNXfn+3jpLmufH61lNJRz936rQ="
  # SONATYPE_PASSWORD
  - secure: "QebHzBALO6+PNQHhaAPBrsQzl/SULuEKT+BAmWlU3G3xDqKvj2BWGdXUHXHuFUi1zGqmMWjakw4kWQL1cR5rj+u/3KAbP1bjsBM5mwOKgFKR92DiU1veeUdNaZYKPMHXXc5FKRbFD3qsR7s0pCf95i0W72FFXWQgp4GAgD3d+20="
  # COVERALLS_TOKEN
  - secure: IxE/hQMkpTshpL4nCCmtp9bV/YH85Svwjl6epVfQaKOwhMVtj9YUCgeuFJwh4ZUB6n+bIQr9sAq5jbBeomWbA04AdbXjuYPTnVgWBqitnY0dVTMpa/WS5mLcOkJCbAnYstNNwmeEifrhHP5hEWBTU9dx1aUClbcR0l3grjZE5D0=
  # SONAR_USER
  - secure: "Y0Hs0R/TncCka+m4aP2Dmn9J3PBm+gssKnttoYDGb8H5tDsMYRy+kxNhkGwqUdJnQRuth5583CYK8UzxYGeDzWDB+zCx7qiSzXblc2VG5sGSCBXBdmh8E100n+W9t02zjJpKGGqOrFvAbgkkaiGjsJB6FhUO19s4EaNeoAE5EnE="
  # SONAR_PASSWORD
  - secure: "N84js3IKpRatJp7XPRcIFbCJAIgn2ugnBnF62afi8L9f/SXnXlFfRYmeHyPMTSN2ivjFJ3dhePyOPvjEOlQcYZp3ZqL7nAWL56O9B5GFZaOsUEGZcknE14yRARYR5aLIP6kICuEcvHiYMGrfiTispE9ZQW4391gzvVVpPauX8J8="
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/12b880d9f4086ef2a62c
    on_success: always
    on_failure: always
    on_start: never
