language: java
sudo: false
dist: trusty
jdk:
- oraclejdk8
- oraclejdk9
- oraclejdk11
- oraclejdk13
- openjdk8
cache:
  directories:
  - $HOME/.m2/repository/
  - $HOME/.sonar/cache/
install: mvn --batch-mode dependency:go-offline
script: mvn --batch-mode verify
after_success:
- bash <(curl -s https://codecov.io/bash)
- ./etc/maybe-sonar.sh
deploy:
  skip_cleanup: true
  provider: script
  script: mvn --batch-mode --settings etc/ci-settings.xml deploy
  on:
    repo: grouplens/grapht
    branch: master
    jdk: oraclejdk8
branches:
  except:
  - stable
  - feature/sonar
env:
  global:
  # SONATYPE_USER
  - secure: "CZFHeyoLogfspHNAU2u2LskxKZnAup1znmOTptgMjSuMwVkZ+3czwZIirjv51cxwsYfQGUkA/FdyCCmpjBgDud5WJGteXIOphAj6A415hSZhKtvN10axw9ptx1oSEsvxgyCwa/V4U3vxvs0kgcNXfn+3jpLmufH61lNJRz936rQ="
  # SONATYPE_PASSWORD
  - secure: "QebHzBALO6+PNQHhaAPBrsQzl/SULuEKT+BAmWlU3G3xDqKvj2BWGdXUHXHuFUi1zGqmMWjakw4kWQL1cR5rj+u/3KAbP1bjsBM5mwOKgFKR92DiU1veeUdNaZYKPMHXXc5FKRbFD3qsR7s0pCf95i0W72FFXWQgp4GAgD3d+20="
  # COVERALLS_TOKEN
  - secure: IxE/hQMkpTshpL4nCCmtp9bV/YH85Svwjl6epVfQaKOwhMVtj9YUCgeuFJwh4ZUB6n+bIQr9sAq5jbBeomWbA04AdbXjuYPTnVgWBqitnY0dVTMpa/WS5mLcOkJCbAnYstNNwmeEifrhHP5hEWBTU9dx1aUClbcR0l3grjZE5D0=
  # SONAR_TOKEN
  - secure: Mc3lDFojFojszb8qiVMSv9gRLx8WWbnQ1UlYcIOfd/YxpKIeb4vuZFnRD4gLnkpp+s7ezVrqnddBJ1frfjEusgzvUEocHY9xsRiuGD8F6t2R0abxWbbLJg2yAsCTNXRnqsTPW0wKANKZZJnb1qVAwu2k4URaahlNT9Pr4K7UXZc=
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/12b880d9f4086ef2a62c
    on_success: always
    on_failure: always
    on_start: never
