language: java
jdk:
- oraclejdk7
- oraclejdk8
- openjdk6
install: mvn --batch-mode dependency:go-offline
script: mvn --batch-mode install
branches:
  except:
  - stable
  - feature/sonar
env:
  global:
  # CI_DEPLOY_USER
  - secure: oclpqGyEnHYRhB6idw8rrh3HyHWl0gEQ4o4sOUqegLs+kNJ3Z8pwDSTf5BQzgQD6IQdPGLTTcGxrlrkVV4czZN2ZKvB5XrIIh46cXGTGNiBXL/anV8EXq5uixpDrJEYAQ865UFjVHA8i8i6BxJU7N/kvzXcNKmoNCgIPqPHs3Lc=
  # CI_DEPLOY_PASSWORD
  - secure: fj6wBnUfRIfylO9q3NmBOSFzgjSk+4O2z7ucBWAIGYWcTsviJgHs5ksNaARwe9NFhtMK8ozPfHhCRoJC1NE7j0ewmt44KOX7WegUgEwPlZUdHEyR5PGETKlZltcPGX9MA9C/foWzFq5uS2TxME9N4Ct5RyVqsk0ytgTq5Bk7AUU=
  # COVERALLS_TOKEN
  - secure: IxE/hQMkpTshpL4nCCmtp9bV/YH85Svwjl6epVfQaKOwhMVtj9YUCgeuFJwh4ZUB6n+bIQr9sAq5jbBeomWbA04AdbXjuYPTnVgWBqitnY0dVTMpa/WS5mLcOkJCbAnYstNNwmeEifrhHP5hEWBTU9dx1aUClbcR0l3grjZE5D0=
